source ./folders.config.sh

SCRIPT_DIR=$SCRIPTS_DIR
PHENO_DIR=$PHENO_UPLOAD_DIR
ASSOC_DIR=$GWAS_UPLOAD_DIR
CLEAN_DIR=$CLEANING_DIR
QC_STATS=${PREFIX}/00_SUMMARY/qc-stats.csv

Rscript $SCRIPT_DIR/07_stateOfAffairs.R $PHENO_DIR $ASSOC_DIR $CLEAN_DIR $QC_STATS
